const data=[
    [
    {
        year:1976,
        title:"La recuperación de la democracia",
        body:"La derrota en la guerra de las Malvinas obligó al régimen militar a convocar a elecciones democráticas en 1983 sin poder imponer condiciones. Las dos primeras décadas estuvieron marcadas por la recuperación de la democracia el año en que se inicia el período, el enjuiciamiento a los culpables de violaciones a los derechos humanos durante la dictadura anterior —rasgo que distingue la democracia argentina de las demás democracias recuperadas en Sudamérica—, la crisis de la deuda externa, el inicio de la globalización, las reformas neoliberales y la severa recesión económica iniciada en 1998 que terminó con la crisis generalizada de 2001/2002. El período abarca la primera vez en la historia argentina de dos décadas continuadas bajo régimen democrático y la primera vez en que presidentes democráticos entregan el poder a sucesores de otro partido político elegidos democráticamente.En este período Argentina protagonizará también un importante cambio político y económico, al fundar el Mercosur junto a Brasil, Paraguay y Uruguay.",
    }
    ],
    [

        {
        year:1977,
        title:"",
        body:"",
       } 
    ]
    ,
    [
        {
        year:1978,
        title:"",
        body:"",
    }],
    [
        {
        year:1979,
        title:"",
        body:"",
    }],
    [
        {
        year:1980,
        title:"",
        body:"",
    }],
    [
        {
        year:1981,
        title:"",
        body:"",
    }],
    [
        {
        year:1982,
        title:"",
        body:"",
    }],
    [
        {
        year:1983,
        title:"",
        body:"",
    }],
    [
        {
        year:1984,
        title:"",
        body:"",
    }],
    [
        {
        year:1985,
        title:"",
        body:"",
    }],
    [
        {
        year:1986,
        title:"",
        body:"",
    }],
    [
        {
        year:1987,
        title:"",
        body:"",
    }],
    [
        {
        year:1988,
        title:"Hiperinflación",
        body:"La situación económica se reagravó en 1988 que terminó con una tasa de inflación de 343 %, preludio del estallido de un proceso hiperinflacionario a partir de febrero de 1989 superior al 3000 % anual, que hizo aumentar la pobreza hasta alcanzar un récord histórico hasta entonces: 47,3 %. En esas condiciones se realizaron las elecciones presidenciales del 14 de mayo de 1989, triunfando el candidato opositor, el peronista Carlos Menem con un 47,4 % de los votos, contra el 36,7 % de la UCR. La magnitud del caos económico-social, llevó a Alfonsín a «resignar» al cargo de presidente y anticipar cinco meses el traslado del mando al 8 de julio.",
    }],
    [
        {
        year:1989,
        title:"",
        body:"",
    }],
    [
        {
        year:1990,
        title:"",
        body:"",
    }],
    [
        {
        year:1991,
        title:"",
        body:"",
    }],
    [
    {
        year:1992,
        title:"",
        body:"",
    }
    ],
    [
        {
        year:1993,
        title:"",
        body:"",
    }],
    [
        {
        year:1994,
        title:"",
        body:"",
    }],
    [
        {
        year:1995,
        title:"",
        body:"",
    }],
    [
        {
        year:1996,
        title:"",
        body:"",
    }],
    [
        {
        year:1997,
        title:"",
        body:"",
    }],
    [
        {
        year:1998,
        title:"",
        body:"",
    }],
    [
        {
        year:1999,
        title:"",
        body:"",
    }],
    [
        {
        year:2000,
        title:"",
        body:"",
    }],
    [
        {
        year:2001,
        title:"",
        body:"",
    }],
    [
        {
        year:2002,
        title:"",
        body:"",
    }],
    [
        {
        year:2003,
        title:"",
        body:"",
    }],
    [
        {
        year:2004,
        title:"",
        body:"",
    }],
    [
        {
        year:2005,
        title:"",
        body:"",
    }],
    [
        {
        year:2006,
        title:"",
        body:"",
    }],
    [
        {
        year:2007,
        title:"",
        body:"",
    }],
    [
        {
        year:2008,
        title:"",
        body:"",
    }],
    [
        {
        year:2009,
        title:"",
        body:"",
    }],
    [
        {
        year:2010,
        title:"",
        body:"",
    }],
    [
        {
        year:2011,
        title:"",
        body:"",
    }],
    [
        {
        year:2012,
        title:"",
        body:"",
    }],
    [
        {
        year:2013,
        title:"",
        body:"",
    }],
    [
        {
        year:2014,
        title:"",
        body:"",
    }],
    [
        {
        year:2015,
        title:"",
        body:"",
    }],
    [
        {
        year:2016,
        title:"",
        body:"",
    }],
    [
        {
        year:2017,
        title:"",
        body:"",
    }],
    [
        {
        year:2018,
        title:"",
        body:"",
    }],
    [
        {
        year:2019,
        title:"",
        body:"",
    }],
    [
        {
        year:2020,
        title:"",
        body:"",
    }],
    [
        {
        year:2021,
        title:"",
        body:"",
    }],

]

export default data